package com.home.restful.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-01T09:04:55.598+02:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://controller.restful.home.com/", name = "InsuranceWebservice")
@XmlSeeAlso({ObjectFactory.class})
public interface InsuranceWebservice {

    @WebMethod
    @RequestWrapper(localName = "deleteInsurance", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.DeleteInsurance")
    @ResponseWrapper(localName = "deleteInsuranceResponse", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.DeleteInsuranceResponse")
    public void deleteInsurance(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getInsurances", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.GetInsurances")
    @ResponseWrapper(localName = "getInsurancesResponse", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.GetInsurancesResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public com.home.restful.controller.GetInsurancesResponse.Return getInsurances()
;

    @WebMethod
    @RequestWrapper(localName = "getInsurance", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.GetInsurance")
    @ResponseWrapper(localName = "getInsuranceResponse", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.GetInsuranceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.home.restful.controller.Insurance getInsurance(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateInsurance", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.UpdateInsurance")
    @ResponseWrapper(localName = "updateInsuranceResponse", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.UpdateInsuranceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.home.restful.controller.Insurance updateInsurance(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.home.restful.controller.Insurance arg1
    ) throws ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addInsurance", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.AddInsurance")
    @ResponseWrapper(localName = "addInsuranceResponse", targetNamespace = "http://controller.restful.home.com/", className = "com.home.restful.controller.AddInsuranceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.home.restful.controller.Insurance addInsurance(

        @WebParam(name = "arg0", targetNamespace = "")
        com.home.restful.controller.Insurance arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws ParseException_Exception;
}
