package com.home.restful.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-01T09:59:11.164+02:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "persons-ws",
                  wsdlLocation = "http://localhost:8080/RESTfulWebServicesSample/persons-ws?wsdl",
                  targetNamespace = "http://controller.restful.home.com/")
public class PersonsWs extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controller.restful.home.com/", "persons-ws");
    public final static QName PersonWebservicePort = new QName("http://controller.restful.home.com/", "PersonWebservicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RESTfulWebServicesSample/persons-ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonsWs.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RESTfulWebServicesSample/persons-ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonsWs(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonsWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonsWs() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonsWs(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonsWs(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonsWs(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonWebservice
     */
    @WebEndpoint(name = "PersonWebservicePort")
    public PersonWebservice getPersonWebservicePort() {
        return super.getPort(PersonWebservicePort, PersonWebservice.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonWebservice
     */
    @WebEndpoint(name = "PersonWebservicePort")
    public PersonWebservice getPersonWebservicePort(WebServiceFeature... features) {
        return super.getPort(PersonWebservicePort, PersonWebservice.class, features);
    }

}
