
package com.home.restful.controller;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-01T09:59:11.113+02:00
 * Generated source version: 3.4.5
 *
 */
public final class PersonWebservice_PersonWebservicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://controller.restful.home.com/", "persons-ws");

    private PersonWebservice_PersonWebservicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonsWs.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonsWs ss = new PersonsWs(wsdlURL, SERVICE_NAME);
        PersonWebservice port = ss.getPersonWebservicePort();

        {
        System.out.println("Invoking addPerson...");
        com.home.restful.controller.Person _addPerson_arg0 = null;
        try {
            com.home.restful.controller.Person _addPerson__return = port.addPerson(_addPerson_arg0);
            System.out.println("addPerson.result=" + _addPerson__return);

        } catch (ParseException_Exception e) {
            System.out.println("Expected exception: ParseException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getPersons...");
        com.home.restful.controller.GetPersonsResponse.Return _getPersons__return = port.getPersons();
        System.out.println("getPersons.result=" + _getPersons__return);


        }
        {
        System.out.println("Invoking updatePerson...");
        int _updatePerson_arg0 = 0;
        com.home.restful.controller.Person _updatePerson_arg1 = null;
        try {
            com.home.restful.controller.Person _updatePerson__return = port.updatePerson(_updatePerson_arg0, _updatePerson_arg1);
            System.out.println("updatePerson.result=" + _updatePerson__return);

        } catch (ParseException_Exception e) {
            System.out.println("Expected exception: ParseException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getPerson...");
        int _getPerson_arg0 = 0;
        com.home.restful.controller.Person _getPerson__return = port.getPerson(_getPerson_arg0);
        System.out.println("getPerson.result=" + _getPerson__return);


        }
        {
        System.out.println("Invoking deletePerson...");
        int _deletePerson_arg0 = 0;
        port.deletePerson(_deletePerson_arg0);


        }

        System.exit(0);
    }

}
